@startuml
'https://plantuml.com/class-diagram

class Person {
    +name
    +email
}

class Mentor {
    +centre
}

class Student {
    +centre
    +mentor
}

Person <|-- Mentor
Person <|-- Student

Student --> Mentor : mentored by

@enduml
